name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 1: Software Composition Analysis (SCA) 
      # Ye check karega ke axios aur lodash ke purane versions mein kya masle hain
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # Takay pipeline rukay nahi aur hum results dekh sakein
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 2: Secret Scanning
      # Ye check karega ke ghalti se koi API key to push nahi ho gayi
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

      - name: Build Docker Image
        run: docker build -t threat-monitor-app:latest .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'threat-monitor-app:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
